[v1.18.x] fabtests/common: Avoid using memset function name
This causes a compile error on MacOS with clang 14.0.0 because memset is
substituted as a builtin function by the preprocessor.

common/hmem.c:172:25: error: no member named '__builtin___memset_chk' in 'struct ft_hmem_ops'
        return hmem_ops[iface].memset(device, buf, value, size);
               ~~~~~~~~~~~~~~~ ^

Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
(cherry picked from commit dd2ce59b61a538a8b3b9e137ac05e83b062cd851)