prov/verbs: check the presence of rdmacm_create_qp_ex for XRC
The code for XRC requires the support of rdmacm_create_qp_ex, which
is not always available. On some platforms like Centos 7.x, this
would result in an error due to implicit declaration of function
rdma_create_qp_ex:

prov/verbs/src/verbs_domain_xrc.c:89:2: warning: implicit declaration
of function 'rdma_create_qp_ex' [-Wimplicit-function-declaration]

Signed-off-by: Sylvain Didelot <sdidelot@ddn.com>