prov/efa: Fix conflicting types for efa_mock_efa_ibv_cq_wc_read_opcode_return_mock
prov/efa/test/efa_unit_test_mocks.c:171:10: warning: conflicting types
for ‘efa_mock_efa_ibv_cq_wc_read_opcode_return_mock’ due to enum/integer
mismatch; have ‘uint32_t(struct efa_ibv_cq *)’ {aka ‘unsigned int(struct efa_ibv_cq *)’} [-Wenum-int-mismatch]
  171 | uint32_t efa_mock_efa_ibv_cq_wc_read_opcode_return_mock(struct efa_ibv_cq *current)

Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>