headers: fix forward-declaration of enum fi_collective_op with C++
Compiling the fi_domain.h header with C++ compiler ends up to the
following error:

include/rdma/fi_domain.h:206:8: error: use of enum 'fi_collective_op'
without previous declaration  enum fi_collective_op;

In C++, storage required for the enum variables is determined
by the compiler, whilst it is always an integer with C.

As a consequence, C++ doesn't allow to forward-declare an enum
without specifying its actual size.

The suggested fix is to move the declaration of the enum
fi_collective_op to fi_domain.h. It should be fine as fi_collective.h
does include fi_domain.h anyway.

Signed-off-by: Sylvain Didelot <sdidelot@ddn.com>