prov/efa: Add missing thread safty annotation for qp_table
Fix ./prov/efa/src/efa_data_path_direct_entry.h:186:23: error: reading variable 'qp_table' requires holding mutex 'efa_qp_table_lock_sym'.
Hot-path function intentionally reads qp_table without the lock as
it is protected by generation count validation.

Fix prov/efa/src/efa_base_ep.c:445:4: error: calling function 'efa_base_ep_destruct_qp_unsafe' requires holding mutex 'efa_qp_table_lock_sym' exclusively.
Add OFI_TSA_REQUIRES to the caller efa_base_ep_create_qp.

Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>