add fi_strerror utility
Not infrequently, I find myself with the numeric return value from a
libfabric function but no easy way to call fi_strerror(3).  This commit
adds a small developer utility called fi_strerror that does what you
would expect.

```
$ fi_strerror
Usage: fi_strerror FI_ERROR_CODE

Displays the error string for the given numeric FI_ERROR_CODE.
FI_ERROR_CODE may be a hexadecimal, octal, or decimal constant.
For convenience, the absolute value of FI_ERROR_CODE will be used.
$ fi_strerror BOGUS
ERROR: unable to parse 'BOGUS'

Usage: fi_strerror FI_ERROR_CODE

Displays the error string for the given numeric FI_ERROR_CODE.
FI_ERROR_CODE may be a hexadecimal, octal, or decimal constant.
For convenience, the absolute value of FI_ERROR_CODE will be used.
$ fi_strerror 5
Input/output error
$ fi_strerror 0x107
Missing or unavailable completion queue
$ fi_strerror -0x107
Missing or unavailable completion queue
```

Signed-off-by: Dave Goodell <dgoodell@cisco.com>