prov/verbs: Fix compilation error with anonymous union member initialization
Intel compiler 2018.3.222 generates errors when compiling verbs provider with
rdma-core 34.1:

prov/verbs/src/verbs_rma.c(170): error: a designator for an anonymous union
member can only appear within braces corresponding to that anonymous union
                .imm_data = htonl((uint32_t)data)

It's a compiler specific limitation and has been fixed in later Intel compilers.
Change to use assignment statement for better compatibility.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>