[v1.13.x] include: Fix compilation error
Include stdbool.h to fix a compilation error:
expected specific-qualifier-list before 'bool'

Signed-off-by: Jie Zhang <zhngaj@amazon.com>
(cherry picked from commit af552c800a3546e45b5528b80492ee414e75103a)