log: Fix undefined __format__ attribute detected by AppVeyor on Windows
AppVeyor complains about the patch series with the following error:
  c:\projects\libfabric\include\rdma\providers\fi_log.h(75):
	error C2061: syntax error: identifier '__attribute__' [C:\projects\libfabric\libfabric.vcxproj]
  c:\projects\libfabric\include\rdma\providers\fi_log.h(75):
	error C2059: syntax error: ';' [C:\projects\libfabric\libfabric.vcxproj]
  c:\projects\libfabric\include\rdma\providers\fi_log.h(75):
	error C2059: syntax error: 'constant' [C:\projects\libfabric\libfabric.vcxproj]

I believe it occurs because the __format__ GCC attribute is undefined
on Windows platforms.

Signed-off-by: Sylvain Didelot <sdidelot@ddn.com>