hmem/rocr: fix issue introduced by 43e92bf82a
43e92bf82a introduce a build breakage for earlier versions of rocm.
The DMA buf defines were added to handle compatibility, but were
not added around the callback functions. This led to compile error
with older version of the rocm API:

src/hmem_rocr.c:182:36:
  error: ‘hsa_amd_portable_export_dmabuf’ undeclared here (not in a function)
    .hsa_amd_portable_export_dmabuf = hsa_amd_portable_export_dmabuf,

Also made a few changes to clean up warnings and code style.

Signed-off-by: Amir Shehata <shehataa@ornl.gov>