prov/efa/test: Fix compiler warning about format truncation
prov/efa/test/efa_unit_test_info.c:299:25: error: ‘%d’ directive output may
be truncated writing between 1 and 10 bytes into a region of size 7
[-Werror=format-truncation=]
    snprintf(env_str, 7, "%d", env_val);
                          ^~

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>
(cherry picked from commit 9f6d6d252db8cc1d7eafde734d63af9e14a02833)